# Generated by Django 3.0.7 on 2023-04-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_remove_saleitem_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='kannur', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(default='kerala', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='street',
            field=models.CharField(default='indevaram', max_length=50),
            preserve_default=False,
        ),
    ]
