# Generated by Django 3.0.7 on 2023-04-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20230408_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='house',
            field=models.CharField(default='sreen', max_length=50),
            preserve_default=False,
        ),
    ]
