# Generated by Django 3.0.7 on 2023-04-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20230408_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
